### PR TITLE
maint/flow

### PR DESCRIPTION
**Pull request by mnicpt**
- Fixes flow error
- Fix babel env presets for flow and react
- Updated dependencies

### CODE REVIEW

**Comment by mstuart** [comment]
Tests pass? Thinking we should drop a .travis.yml file in here so that tests run on PRs.

**Comment by mstuart** [comment]
Nevermind. There's a test/ directory, but no tests :)

**Comment by bluepnume** [comment]
@mstuart yeah we do have tests under `npm t` so we totally should run this in travis

**Comment by mstuart** [comment]
Oops, missed those. Sounds good. Will add a travis file.

**Comment by mnicpt** [comment]
@mstuart The tests passed before.  But see you are adding the travis file.

**Pull request merged**
