### PR TITLE
chore: switch to dart sass

### PR DESCRIPTION
**Pull request by Seavenly**
[node-sass](https://www.npmjs.com/package/node-sass) has been deprecated and the current version of `node-sass` is not compatible with the newer M1 Mac architecture, making it challenging to install `grumbler-scripts` as a dependency while developing. Are we able to swap out to the newer Dart Sass (`sass`) package?

### CODE REVIEW

**Comment by westeezy** [comment]
This change makes sense to me. @Seavenly is your team using scss for styling? I can publish an alpha if it helps for testing purposes otherwise I'm willing to publish a new version for this.

**Review by gregjopa — APPROVED** [review]

**Comment by Seavenly** [comment]
We do currently use scss styling for [our modal](https://github.com/paypal/paypal-messaging-components/tree/develop/src/components/modal/v2/styles) which we compile using the same common webpack config as the core SDK messaging component. Happy to verify the change.

**Comment by westeezy** [comment]
Thanks for the additional info @Seavenly. Let's aim to have an alpha published for testing sometime today and we can chat offline when we confirm everything looks good on our ends. I'll do a quick audit of usage of sass in the other components as well, but I am not anticipating any issues here so mostly just due diligence.

**Comment by westeezy** [comment]
please see `@krakenjs/grumbler-scripts@7.0.1-alpha.1` for testing this out!

**Pull request merged**
