### PR TITLE
chore: update eslint

### PR DESCRIPTION
**Pull request by westeezy**
- update to use the @babel/eslint-parser to resolve imports properly
  from the import plugin
- update all packages to recent versions
- set `requireConfigFile` to false for @babel/eslint-parser to be able
  to scan older packages in `node_modules`

### CODE REVIEW

**Comment by westeezy** [comment]
@nbierdeman i think 5.2.0 should work for the typescript parser, but can you confirm please and thank you? <3

**Comment by westeezy** [comment]
`find-eslint-rules` has an active PR for updating to eslint v8 here https://github.com/sarbbottam/eslint-find-rules/issues/336. This is why we have a CI failure so let's await those updates.

**Review by nbierdeman — COMMENTED** [review]
@westeezy, I'm also getting that `eslint-find-rules` error locally:

Screen Shot 2021-11-01 at 1 57 17 PM

**Comment by westeezy** [comment]
`eslint-find-rules` release v4 today which works with eslint v8. This also is exposing a lot more unused rules than previous so I'll take a peek and see if its false positive or accurate. Kinda stinks that we paste in like all the rules rather than just the ones we change from default :(

**Comment by westeezy** [comment]
lets set `find-eslint-rules` to not error for now. I've never been a big fan of that tool when you have lots of eslint plugins. We can update that later as time permits.

**Review by wsbrunson — APPROVED** [review]

**Review by wsbrunson — APPROVED** [review]

**Pull request merged**
